image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - export TEST_NAME=test\ducktales.tests\ducktales.tests.csproj
          - dotnet restore
          
          - dotnet build
          - dotnet test $TEST_NAME