image: microsoft/dotnet:sdk

pipelines:
  branches:
    master:
      - step:
          caches:
            - dotnetcore
          script:
            - dotnet restore
            - dotnet build
            - dotnet test test/ducktales.tests/ducktales.tests.csproj