image: andrecastrogarcia/dotnet-sonar:latest

pipelines:
  default:
    - step:
        name: Sonar Quality Gate
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet /sonar/SonarScanner.MSBuild.dll begin /k:"ducktales" /d:sonar.branch.name="$BITBUCKET_BRANCH" /d:sonar.branch.target="master" /d:sonar.organization="$SONAR_ORGANIZATION" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_PROJECT_LOGIN" /d:sonar.cs.opencover.reportsPaths="test/ducktales.tests/coverage/coverage.opencover.xml"
          - dotnet build
          - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=coverage /p:Exclude="[NUnit3.*]*" test/ducktales.tests/ducktales.tests.csproj
          - dotnet /sonar/SonarScanner.MSBuild.dll end /d:sonar.login="$SONAR_PROJECT_LOGIN"
  branches:
    master:
      - step:
          name: Sonar Quality Gate
          caches:
            - dotnetcore
          script:
            - dotnet restore
            - dotnet /sonar/SonarScanner.MSBuild.dll begin /k:"ducktales" /d:sonar.organization="$SONAR_ORGANIZATION" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_PROJECT_LOGIN" /d:sonar.cs.opencover.reportsPaths="test/ducktales.tests/coverage/coverage.opencover.xml"
            - dotnet build
            - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=coverage /p:Exclude="[NUnit3.*]*" test/ducktales.tests/ducktales.tests.csproj
            - dotnet /sonar/SonarScanner.MSBuild.dll end /d:sonar.login="$SONAR_PROJECT_LOGIN"